version: "3"

services:

  huionlune_backend:
    container_name: huionlune_backend
    image: huionlune_backend:v0.0.1

    ports:
      - "8088:8088"

    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=8088'
    command: flask run --host=0.0.0.0 --port=8088
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"

    env_file:
      - .env

    restart: on-failure
    volumes:
    # Path on the host, relative to the Compose file
      - ./app:/app